# Site settings
title: Willem van der Jagt
# email: wkjagt@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Willem van der Jagt. Father of 3 angels, lead geek at @CakeMail,
    and absorber of interesting information.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://willemvanderjagt.com" # the base hostname & protocol for your site
twitter_username: wkjagt
github_username:  wkjagt
linked_in_url: https://www.linkedin.com/in/willemvanderjagt

# Build settings
markdown: kramdown

highlighter: pygments